/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.3.0   2020-10-11

The MIT License (MIT)
Copyright (c) 2019 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f0xx.h"
#include "spi.h"
#include "tft.h"
#include "usart.h"

/* Private macro */
/* Private variables */
/* Private function prototypes */
/* Private functions */

/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/

extern cBuffer rx_buffer;

uint8_t data_for_spi[16];
uint8_t data_for_spi_ready = 0;
uint8_t size_data_spi = 0;


void ProcessCmd() {
	if (bufferHaveData(&rx_buffer) == 0) {
		return;
	}

	uint8_t current_byte = bufferGetFromFront(&rx_buffer);
	USART1->TDR = current_byte;

	static uint8_t status = 0;
	static uint8_t ptrData = 1;
	static uint8_t size_cmd;

	switch(status) {
		case 0 :	//sync
			if (current_byte == 0x7A) {
				++status;
				ptrData = 1;
			}
		break;
		case 1 :	//size
			size_cmd = current_byte;
			size_data_spi = size_cmd;
			++status;
		break;

		case 2 :	//cmd
			data_for_spi[0] = current_byte;
			++status;
		break;
		case 3 :	//data
			data_for_spi[ptrData] = current_byte;
			++ptrData;
			if (ptrData > size_cmd) {
				status = 0;
				data_for_spi_ready = 1;
			}
		break;
	}
}

void SendToDisplay() {
	if (data_for_spi_ready == 0)
		return;
	tft_write_cmd(data_for_spi[0], &data_for_spi[1], size_data_spi);
	data_for_spi_ready = 0;
}



int main(void)
{
//	uint16_t data_spi = 0;
//
//	spi1_master_init();
//	spi2_slave_init();

	usart1_init();
	tft_init();


	/* Infinite loop */
	while (1)
	{
		ProcessCmd();
		SendToDisplay();
	}
}





